# This file was generated by GoReleaser. DO NOT EDIT.
class Tss < Formula
  desc "A Go port of moreutils/ts and fork of kevinburke/tss"
  homepage "https://github.com/peaceiris/tss"
  version "0.1.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peaceiris/tss/releases/download/v0.1.3/tss_v0.1.3_darwin-amd64.tar.gz"
    sha256 "343097e43ea345896499ca05cbb67cabfd631252b8ed77b015a997bfdc0f7a2a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/peaceiris/tss/releases/download/v0.1.3/tss_v0.1.3_linux-amd64.tar.gz"
    sha256 "ca527e52ecb951572e0a15d87fcb6dc38ad7e936a478c78a49aa4a6695e42beb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/peaceiris/tss/releases/download/v0.1.3/tss_v0.1.3_linux-arm64.tar.gz"
    sha256 "734e65162b82b92332d6f31eded4dd3dc9e05e5d6e1ceded8d8df0c9f51dc685"
  end

  def install
    bin.install "tss"
  end

  test do
    system "#{bin}/tss -h"
  end
end
