# This file was generated by GoReleaser. DO NOT EDIT.
class Tss < Formula
  desc "A Go port of moreutils/ts and fork of kevinburke/tss"
  homepage "https://github.com/peaceiris/tss"
  version "0.4.0"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/peaceiris/tss/releases/download/v0.4.0/tss_v0.4.0_darwin-amd64.tar.gz"
    sha256 "16f366d6db2ae11f784fe1e2e4120632ec3d3978436769dcdaac789ebc501a6e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/peaceiris/tss/releases/download/v0.4.0/tss_v0.4.0_linux-amd64.tar.gz"
    sha256 "a999c4af7c0530956668a8a6f6d90127b22395dfb7fda0092d058c5fb7093095"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/peaceiris/tss/releases/download/v0.4.0/tss_v0.4.0_linux-arm64.tar.gz"
    sha256 "3c7a3b2eea3e5b4db39c8bdba375d8cd911e8816a91a9e2ff56db60caa2338c7"
  end

  def install
    bin.install "tss"
  end

  test do
    system "#{bin}/tss -h"
  end
end
