# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tss < Formula
  desc "Annotate stdin with timestamps per line. A Go port of moreutils/ts and fork of kevinburke/tss."
  homepage "https://github.com/peaceiris/tss"
  version "0.6.0"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/peaceiris/tss/releases/download/v0.6.0/tss_v0.6.0_darwin-amd64.tar.gz"
      sha256 "66edbbef4691c835266d4d4d8de680f85aa9e565635e916e94f92091148062c5"
    end
    if Hardware::CPU.arm?
      url "https://github.com/peaceiris/tss/releases/download/v0.6.0/tss_v0.6.0_darwin-arm64.tar.gz"
      sha256 "a9906ccda6731be34f67cf036616014645fb91f9a001259f7608b108f64957a2"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/peaceiris/tss/releases/download/v0.6.0/tss_v0.6.0_linux-amd64.tar.gz"
      sha256 "e49df54dae7508d69118fd64a6001bed016e3736565c88ef143f142811b8756a"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/peaceiris/tss/releases/download/v0.6.0/tss_v0.6.0_linux-arm64.tar.gz"
      sha256 "c36d790cf3d1dbb241103476fd167a612747b26cddb179fad6a48a813628100f"
    end
  end

  def install
    bin.install "tss"
  end

  test do
    system "#{bin}/tss -h"
  end
end
