name: Shell

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/shell.yml'
      - '**.sh'
      - 'Makefile'
  pull_request:
    paths:
      - '.github/workflows/shell.yml'
      - '**.sh'
      - 'Makefile'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: make shellcheck
